# Generated by Django 5.2.3 on 2025-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.AddField(
            model_name="customer",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
